# Generated by Django 2.1.3 on 2018-11-14 13:57

import computed_property.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user_start', models.DateTimeField(blank=True, null=True)),
                ('user_end', models.DateTimeField(blank=True, null=True)),
                ('data_start', computed_property.fields.ComputedDateTimeField(blank=True, compute_from='get_data_start', editable=False, null=True)),
                ('data_end', computed_property.fields.ComputedDateTimeField(blank=True, compute_from='get_data_end', editable=False, null=True)),
                ('start', computed_property.fields.ComputedDateTimeField(blank=True, compute_from='get_start', editable=False, null=True)),
                ('end', computed_property.fields.ComputedDateTimeField(blank=True, compute_from='get_end', editable=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Batches',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('value', models.CharField(max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('timestamp', computed_property.fields.ComputedDateTimeField(blank=True, compute_from='get_elapsed', editable=False, null=True)),
                ('elapsed', computed_property.fields.ComputedFloatField(blank=True, compute_from='get_elapsed', editable=False, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_batch', to='BioPyApp.Batch')),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('policy', models.CharField(blank=True, choices=[('Basic128Rsa15', 'Basic128Rsa15'), ('Basic256', 'Basic256'), ('Basic256Sha256', 'Basic256Sha256')], max_length=50, null=True)),
                ('mode', models.CharField(blank=True, choices=[('Sign', 'Sign'), ('SignAndEncrypt', 'SignAndEncrypt')], max_length=50, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='')),
                ('private_key', models.FileField(blank=True, null=True, upload_to='')),
                ('server_certificate', models.FileField(blank=True, null=True, upload_to='')),
                ('timeout', models.IntegerField(default=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('timestamp', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('value', computed_property.fields.ComputedBooleanField(compute_from='get_value', editable=False)),
                ('elapsed', computed_property.fields.ComputedFloatField(blank=True, compute_from='get_elapsed', editable=False, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_batch', to='BioPyApp.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('variable', 'Variable'), ('class', 'Classifier'), ('event', 'Event'), ('spectrum', 'Spectrum')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BioPyApp.Endpoint')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('scale', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('R', 'Raw Materials'), ('C', 'Cleaning'), ('U', 'Upstream'), ('D', 'Downstream'), ('P', 'Packaging')], max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('downstream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='BioPyApp.Process')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('upstream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='BioPyApp.Process')),
            ],
            options={
                'verbose_name_plural': 'Processes',
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('elapsed', computed_property.fields.ComputedFloatField(blank=True, compute_from='get_elapsed', editable=False, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_batch', to='BioPyApp.Batch')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BioPyApp.Process'),
        ),
        migrations.AlterUniqueTogether(
            name='variable',
            unique_together={('batch', 'name', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('endpoint', 'nodeid')},
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('batch', 'name', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('batch', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('process', 'name')},
        ),
    ]
