# Generated by Django 2.1.2 on 2018-11-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioPyApp', 'general_newsletter_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='timeout',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='mode',
            field=models.CharField(blank=True, choices=[('Sign', 'Sign'), ('SignAndEncrypt', 'SignAndEncrypt')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='policy',
            field=models.CharField(blank=True, choices=[('Basic128Rsa15', 'Basic128Rsa15'), ('Basic256', 'Basic256'), ('Basic256Sha256', 'Basic256Sha256')], max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('batch', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('batch', 'name', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='variable',
            unique_together={('batch', 'name', 'timestamp')},
        ),
    ]
